name: ML Pipeline Workflow

on:
  push:
    branches:
      - staging
      - main
      - dev
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Make Predictions
      run: python predict.py
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: liuyingda7701/mlip-app:${{ github.ref_name }}-latest

        
    - name: Push Docker image to Heroku Container Registry
      run: |
        heroku container:login
        docker tag liuyingda7701/mlip-app:${{ github.ref_name }}-latest registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
        docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Release Docker image to Heroku
      run: heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}