name: ML Pipeline Workflow

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Process Data
      run: python data.py
      

    - name: Train Model
      run: python model.py
      

    - name: Make Predictions
      run: python predict.py
    
        
    - name: Build and push Docker image
      
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: liuyingda7701/mlip-app:${{ github.ref_name }}-latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      